services:
  - type: web
    name: lofi-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
